<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <UserSecretsId>todo-e63bb7a1-1644-4dd2-9b51-9f8dbdb6c4ad</UserSecretsId>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <!--#if (IsToAddDocker) -->
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <!--#endif -->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.14"/>
        <PackageReference Include="Asp.Versioning.Http" Version="10.0.0"/>
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0"/>
        <PackageReference Include="Asp.Versioning.OpenApi" Version="10.0.0-rc.1"/>
        <!--#if (IsToExcludeIdentity) -->
        <PackageReference Include="OpenIddict.AspNetCore" Version="7.5.0"/>
        <!--#endif -->
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0"/>
        <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0"/>
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
        <PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Aspire\Aspire.ServiceDefaults\Aspire.ServiceDefaults.csproj"/>
        <ProjectReference Include="..\Todo.Application\Todo.Application.csproj"/>
    </ItemGroup>

</Project>
