<Project Sdk="Aspire.AppHost.Sdk/13.5.2">

    <PropertyGroup>
        <OutputType>Exe</OutputType>

        <UserSecretsId>aspire-cf3293e2-5be6-40c8-ab31-0c4c0334d633</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.5.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Minimal.Api.Template.Presentation.Api\Minimal.Api.Template.Presentation.Api.csproj" AspireProjectMetadataTypeName="Minimal_Api" />
    </ItemGroup>

</Project>
