<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1"/>
        <!--#if (!IsToExcludeIdentity) -->
        <PackageReference Include="OpenIddict.AspNetCore" Version="7.6.0"/>
        <PackageReference Include="OpenIddict.Quartz" Version="7.6.0"/>
        <PackageReference Include="Quartz.Extensions.Hosting" Version="3.19.1"/>
        <!--#endif -->
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Todo.Persistence\Todo.Persistence.csproj"/>
    </ItemGroup>

</Project>
