<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <!--#if (!IsToExcludeIdentity) -->
        <PackageReference Include="OpenIddict.AspNetCore" Version="7.7.0" />
        <PackageReference Include="OpenIddict.Quartz" Version="7.7.0" />
        <PackageReference Include="Quartz" Version="4.0.0" />
        <!--#endif -->
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Minimal.Api.Template.Persistence\Minimal.Api.Template.Persistence.csproj" />
    </ItemGroup>

</Project>